#!/bin/bash

POST_NAME=$1
YEAR=2024

COMMAND_CREATE="hugo new content blog/$YEAR/$POST_NAME.en.md"
echo $COMMAND_CREATE
$COMMAND_CREATE

COMMAND_CREATE="hugo new content blog/$YEAR/$POST_NAME.jp.md"
echo $COMMAND_CREATE
$COMMAND_CREATE
